#!/bin/sh

URL="$1"
if [ -z $URL]; then
       echo "pls retry with  a valid url.For example : /aria_add http://example.com/file.ext"

else
      curl http://127.0.0.1:6800/jsonrpc -X POST --data '{"jsonrpc": "2.0","id":"foo", "method": "aria2.addUri", "params":[["'"$URL"'"]]}' 
    
fi

